# Spring Boot Application
spring.application.name=aj-server
server.port=8080

# MongoDB Connection
# Not: MongoDB'nin bu adreste çal??t???ndan emin olun. Farkl? bir adreste ise güncelleyin.
spring.data.mongodb.uri=mongodb://localhost:27017/aj-international

# JWT Secret Key (Güvenlik için bu de?eri daha sonra karma??k ve uzun bir Base64 anahtar ile de?i?tirin)
jwt.secret=bXktc2VjcmV0LWtleS1mb3ItYWotc3ByaW5nLWJvb3Qtand0LWFwcGxpY2F0aW9uLW11c3QtYmUtbG9uZw==

# JWT Expiration Time (milisaniye cinsinden - 1 gün)
jwt.expiration=86400000

file.upload-dir=./uploads

# Dosya Yükleme Limitleri
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB